### ISSUE TITLE
Can't add control

### ISSUE THREAD

**Issue by SandPox** [viperneo/winforms-modernui#260]
In this latest version almost all metroframework control falls down to the box below form design (regular control work fine).

![Alt text](http://i.stack.imgur.com/6wE0W.png)

**Comment by fozzedout** [comment]
you need to add the Metroframework.Design.dll to your project

**Comment by SandPox** [comment]
yes, i already added but still same result
even i build the source and run the demo file it gave me this error


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MetroFramework.Forms.MetroForm.WndProc(Message& m) in d:\Downloads\winforms-modernui-master\winforms-modernui-master\MetroFramework\Forms\MetroForm.cs:line 590
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
MetroFramework.Demo
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Downloads/winforms-modernui-master/winforms-modernui-master/MetroFramework.Demo/bin/Debug/MetroFramework.Demo.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MetroFramework
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Downloads/winforms-modernui-master/winforms-modernui-master/MetroFramework.Demo/bin/Debug/MetroFramework.DLL
----------------------------------------
System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_64/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MetroFramework.Fonts
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Downloads/winforms-modernui-master/winforms-modernui-master/MetroFramework.Demo/bin/Debug/MetroFramework.Fonts.DLL
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Design
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Design/2.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by fozzedout** [comment]
Just to clarify: that happens when you run the demo through Visual Studio?
I've seen those errors whe  you are trying to run it outsdide.
Also, what version of the Windows and Visual Studio are you using?

**Comment by SandPox** [comment]
I'm running VS2013 on Windows 7 x64
![capture](https://cloud.githubusercontent.com/assets/8336751/7665360/c14a8540-fbdd-11e4-867d-c090b957c775.PNG)
there's a guy fixed this NullRefException here: https://github.com/marzeg/winforms-modernui/commit/4e5d9b0fd7cdfaac6bd55b81835d7912b262e476 but the control still not visable on GUI when I use his version

**Comment by fozzedout** [comment]
As, use either my main or testing fork

**Comment by SandPox** [comment]
yes yes yes!! your main working fine with me, thanks
