### ISSUE TITLE
MetroGrid throws ArgumentOutOfRangeException when mouse click occurs on vertical scrollbar beneath the bar/thumb in an attempt to scroll down

### ISSUE THREAD

**Issue by ryangithubber** [viperneo/winforms-modernui#275]
MetroGrid throws ArgumentOutOfRangeException when mouse click occurs on vertical scrollbar in the area beneath the actual bar/thumb in an attempt to scroll down. This also occurs when clicking on the bar/thumb on the vertical scrollbar, and then and pressing the down arrow key to scroll down. 

Sometimes it takes several clicks before this will occur, depending on the number of items in the grid and how much scrolling needs to occur to reach the bottom of the list. It appears as if the scrollbar is not completely scrolling to the bottom when we are actually at the bottom of the list, leaving a remaining area beneath the bar that the user can click. And when it is clicked, the control thinks we are at the bottom of the list (and we rightfully are), but there is still room in the scrollbar to scroll further down. Probably an issue with the row index, similar to Issue #238. 

![2015-05-27_21-04-23](https://cloud.githubusercontent.com/assets/12634132/7851406/e1d3ea7e-04b4-11e5-8c06-77de371710d1.jpg)

**Comment by ryangithubber** [comment]
This is the message I receive: 

---
> 
System.ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
Parameter name: value
  Source=System.Windows.Forms
  ParamName=value
  StackTrace:
       at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
       at MetroFramework.Controls.MetroDataGridHelper._scrollbar_Scroll(Object sender, ScrollEventArgs e)
       at MetroFramework.Controls.MetroScrollBar.OnScroll(ScrollEventType type, Int32 oldValue, Int32 newValue, ScrollOrientation orientation)
       at MetroFramework.Controls.MetroScrollBar.ProgressThumb(Boolean enableTimer)
       at MetroFramework.Controls.MetroScrollBar.OnMouseDown(MouseEventArgs e)
       at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at MyApp.Program.Main() in c:\myapp\Program.cs:line 19
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
</code>
---

Program.cs line 19 contains this: 
<code>
Application.Run(new Form1());</code>

And Form1 simply has the MetroGrid control on the form.

**Comment by mobedi** [comment]
has this issue been resolved yet?

**Comment by mobedi** [comment]
I read on StackOverflow that running the `PerformLayout()` method of the `DataGridView` will solve the problem. But I cannot find such function on `MetroGrid`.

**Comment by mobedi** [comment]
@ryangithubber I found a solution to silence this exception for now. Check the **Solved** part of my post: https://github.com/viperneo/winforms-modernui/issues/297
