### ISSUE TITLE
Setting Property 'MaximizeBox' to false on the form causes NullRefrenceException

### ISSUE THREAD

**Issue by dylanpdx** [viperneo/winforms-modernui#313]
Using the sample application and any other application, if MaximizeBox is set to false, the program throws a NullRefrenceException:

    System.NullReferenceException was unhandled
      Message=Object reference not set to an instance of an object.
      Source=MetroFramework
      StackTrace:
           at MetroFramework.Forms.MetroForm.WndProc(Message& m) in C:\Users\Dylan\Documents\GitHub\winforms-modernui\MetroFramework\Forms\MetroForm.cs:line 590
           at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
           at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
           at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
           at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
           at System.Windows.Forms.Form.DefWndProc(Message& m)
           at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
           at System.Windows.Forms.Control.WndProc(Message& m)
           at System.Windows.Forms.Form.WmWindowPosChanged(Message& m)
           at MetroFramework.Forms.MetroForm.WndProc(Message& m) in C:\Users\Dylan\Documents\GitHub\winforms-modernui\MetroFramework\Forms\MetroForm.cs:line 581
           at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
           at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
      InnerException: 

I beleive the error occurs here:
`MetroForm.cs:line 590`

**Comment by dylanpdx** [comment]
Nevermind, I saw the other branch to fix it.
